name: cd
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install depencies
        run: npm install
        working-directory: ./How-About-This-Front-
      - name: Build
        run: npm run build
        working-directory: ./How-About-This-Front-/build
      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://how-about-this-ver1 \
            --delete
        working-directory: ./How-About-This-Front-/build
        
  
