name: cd 
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install depencies
        run: npm install
        working-directory: ./
      - name: Build
        run: CI='false' npm run build
        working-directory: ./
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
              aws-access-key-id: ${{secrets.S3_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{secrets.S3_SECRET_ACCESS_KEY}}
              aws-region: ap-northeast-2
      - name: Upload build to S3
        env:
          BUCKET: ${{ secrets.S3_BUCKET_NAME}}
        run: |
          aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          build s3://$BUCKET/build \
          --delete
        
  
